<a href="https://colab.research.google.com/github/mothukuriv/ML/blob/master/ML_programing_A2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:

# Importing the dataset
dataset = pd.read_csv('Bank_Predictions.csv')

In [0]:
dataset.head()

Number  Customer_ID Last_Name  ...  IsActiveMember Customer_Salary Acc_Closed
0       1     15634602  Hargrave  ...               1       101348.88          1
1       2     15647311      Hill  ...               1       112542.58          0
2       3     15619304      Onio  ...               0       113931.57          1
3       4     15701354      Boni  ...               0        93826.63          0
4       5     15737888  Mitchell  ...               1        79084.10          0

[5 rows x 14 columns]

In [0]:
dataset

Number  Customer_ID  ... Customer_Salary  Acc_Closed
0          1     15634602  ...       101348.88           1
1          2     15647311  ...       112542.58           0
2          3     15619304  ...       113931.57           1
3          4     15701354  ...        93826.63           0
4          5     15737888  ...        79084.10           0
...      ...          ...  ...             ...         ...
9995    9996     15606229  ...        96270.64           0
9996    9997     15569892  ...       101699.77           0
9997    9998     15584532  ...        42085.58           1
9998    9999     15682355  ...        92888.52           1
9999   10000     15628319  ...        38190.78           0

[10000 rows x 14 columns]

In [0]:
# Encoding categorical data
dataset.drop(columns = ['Number', 'Customer_ID', 'Last_Name'])

Cr_Score Location  Gender  ...  IsActiveMember  Customer_Salary  Acc_Closed
0          619   France  Female  ...               1        101348.88           1
1          608    Spain  Female  ...               1        112542.58           0
2          502   France  Female  ...               0        113931.57           1
3          699   France  Female  ...               0         93826.63           0
4          850    Spain  Female  ...               1         79084.10           0
...        ...      ...     ...  ...             ...              ...         ...
9995       771   France    Male  ...               0         96270.64           0
9996       516   France    Male  ...               1        101699.77           0
9997       709   France  Female  ...               1         42085.58           1
9998       772  Germany    Male  ...               0         92888.52           1
9999       792   France  Female  ...               0         38190.78           0

[10000 rows x 11 columns]

In [0]:
np.array(dataset.drop(columns = ['Number', 'Customer_ID', 'Last_Name']))

array([[619, 'France', 'Female', ..., 1, 101348.88, 1],
       [608, 'Spain', 'Female', ..., 1, 112542.58, 0],
       [502, 'France', 'Female', ..., 0, 113931.57, 1],
       ...,
       [709, 'France', 'Female', ..., 1, 42085.58, 1],
       [772, 'Germany', 'Male', ..., 0, 92888.52, 1],
       [792, 'France', 'Female', ..., 0, 38190.78, 0]], dtype=object)

In [0]:
np.array(dataset['Acc_Closed'])

array([1, 0, 1, ..., 1, 1, 0])

In [0]:
X = dataset.iloc[:, 3:13].values
Y = dataset.iloc[:, 13].values

In [0]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [0]:

from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

label_encoder = LabelEncoder()

X[:,1] = label_encoder.fit_transform(X[:,1])
X[:,2] = label_encoder.fit_transform(X[:,2])




In [0]:
X, Y

(array([[619, 0, 0, ..., 1, 1, 101348.88],
        [608, 2, 0, ..., 0, 1, 112542.58],
        [502, 0, 0, ..., 1, 0, 113931.57],
        ...,
        [709, 0, 0, ..., 0, 1, 42085.58],
        [772, 1, 1, ..., 1, 0, 92888.52],
        [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object),
 array([1, 0, 1, ..., 1, 1, 0]))

In [0]:
transformer = ColumnTransformer(
    transformers=[
        ("hc",   
         OneHotEncoder(), 
         [1]             
         )
    ],
    remainder = 'passthrough'
)
X = transformer.fit_transform(X)

In [0]:
X = X[:, 1:]

In [0]:
# Splitting the dataset into the Training and Test sets

# Feature Scaling
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

scale = StandardScaler()

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

X_train = scale.fit_transform(X_train)
X_test = scale.transform(X_test)


In [0]:
# ------- Part-2: Build the ANN --------

# import keras library and packages
import keras

from keras.models import Sequential
from keras.layers import Dense



Using TensorFlow backend.


In [0]:
# Initializing the ANN

classifier = Sequential()



In [0]:

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11 ))

# Adding second hidden layer

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))



In [0]:
# Compiling the ANN
classifier.compile(optimizer = 'adam',loss= "binary_crossentropy", metrics=["accuracy"])


In [0]:
# Fitting the ANN to the training set
classifier.fit(X_train, Y_train, batch_size = 10, epochs = 200  )

Epoch 1/200
7000/7000 [==============================] - 1s 117us/step - loss: 0.3953 - acc: 0.8363
Epoch 2/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3950 - acc: 0.8363
Epoch 3/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3945 - acc: 0.8374
Epoch 4/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3946 - acc: 0.8373
Epoch 5/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3946 - acc: 0.8367
Epoch 6/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3944 - acc: 0.8386
Epoch 7/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3943 - acc: 0.8376
Epoch 8/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3941 - acc: 0.8374
Epoch 9/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3938 - acc: 0.8377
Epoch 10/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3935 - acc: 0.8389

In [0]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)


In [0]:
y_pred = (y_pred > 0.5)
y_pred


array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [0]:

# Making the confusion Matrix

from sklearn.metrics import confusion_matrix
output_matrix = confusion_matrix(Y_test, y_pred)

In [0]:
output_matrix

array([[2262,  117],
       [ 354,  267]])